export const Labels = {
    homeHeader: "Minhas Plantas",
    newPlantHeader: "Nova Planta",
    searchBarPlaceholder: "Encontrar plantas",
    emptyHomeLabel: "Clique aqui para cadastrar sua planta!",
    species: "Espécie",
    size: "Porte",
    resistence: "Resistência",
    poison: "Veneno",
    infos: "Infos",
    level: "Nível",
    edit: 'Editar',
    water: 'Água',
    soil: 'Terra',
    sun: 'Sol',
    fertilizer: 'Adubo',
    seeHistory: 'Ver Histórico',
    goBack: 'Voltar',
    informations: 'Informações',
    watering: 'Rega',
    light: 'Luz',
    changeSoil: 'Troca de Terra',
    fertilizer2: 'Fertilizante',
    cancel: 'Cancelar',
    delete: 'Deletar Planta'
}