export const Labels = {
    homeHeader: "Minhas Plantas",
    newPlantHeader: "Nova Planta",
    searchBarPlaceholder: "Encontrar plantas",
    emptyHomeLabel: "Clique aqui para cadastrar sua planta!",
    species: "Espécie",
    size: "Porte",
    resistence: "Resistência",
    poison: "Veneno",
    infos: "Infos",
    level: "Nível",
    edit: 'Editar',
    water: 'Água',
    soil: 'Terra',
    sun: 'Sol',
    fertilizer: 'Adubo',
    seeHistory: 'Ver Histórico',
    goBack: 'Voltar',
    informations: 'Informações',
    watering: 'Rega',
    light: 'Luz',
    changeSoil: 'Troca de Terra',
    fertilizer2: 'Fertilizante',
    cancel: 'Cancelar',
    delete: 'Deletar Planta',
    confirm: 'Confirmar',
    splashScreenNext: 'Continuar',
    splashScreenDone: 'Vamos Começar!',
    splashScreenSkip: 'Pular',
    splashScreenTitle1: 'O início',
    splashScreenText1: 'Era um dia como qualquer outro, em que nada poderia dar errado. Até que... As primeiras pragas começaram a aparecer!',
    splashScreenTitle2: 'As pragas',
    splashScreenText2: 'Elas chegaram para aterrorizar a vida das plantinhas e destruir os jardins da vizinhança!',
    splashScreenTitle3: 'Os cuidados',
    splashScreenText3: 'Mas nem tudo está perdido! Basta manter as plantinhas com os cuidados em dia, regando e adubando quando necessário!',
}